name: Redirect Updater

on:
  schedule:
  - cron:  '30 0 * * *'
  # - cron:  '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    name: run
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: 'gh-pages'

    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Update redirects
      run: make

    - name: Commit files
      run: |
        git config --local user.email "redirects-action@vim-jp.org"
        git config --local user.name "GitHub Action"
        git add --update
        if ! git diff --quiet HEAD ; then
          DATE=$(date "+%Y/%m/%d %H:%M %Z")
          git commit -m "Updated by GithubActions at ${DATE}"
          git push
        fi
